# A simple workflow that runs the documented build steps work.

name: Build Instructions
on:
  pull_request:
    branches-ignore:
      - docs
    paths-ignore:
      - 'docs/**'

jobs:

  aswf-docker:
    name: CY2022
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build, install and test (Docker)
      # Note: this _must_ be kept in sync with README.md until we
      # have an established mechanism to test doc-included code.
      run: |
        docker run -v `pwd`:/src aswf/ci-base:2022.2 bash -c '
          cd /src && \
          cmake -S . -B build && \
          cmake --build build && \
          cmake --install build'
