# A simple workflow to run tests using pytest against supported Python versions

name: Tests
on:
  pull_request:
    branches-ignore:
      - docs
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        # We can't properly align to the VFX Reference Platform as this
        # requires glibc 2.17, which is older than any of the available
        # environments.
        config:
        - os: windows-2019
          toolchain: "$USERPROFILE/conan/conan_paths.cmake"
          cmake-additional-args: "-G Ninja"
          sanitizers: OFF
          install-prefix: "$GITHUB_WORKSPACE/dist"

        - os: ubuntu-20.04
          toolchain: "$HOME/conan/conan_paths.cmake"
          sanitizers: ON,
          install-prefix: "$GITHUB_WORKSPACE/dist"

        - os: macos-10.15
          toolchain: "$HOME/conan/conan_paths.cmake"
          # asan needs the pre-load trick for python, ubsan seems to
          # have false positives:
          #   InfoDictionaryTest.cpp:346:25: runtime error:
          #      call to function openassetio_v0_0_InfoDictionary_getBool
          #      through pointer to incorrect function type
          sanitizers: OFF
          install-prefix: "$GITHUB_WORKSPACE/dist"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        # CY2022 (https://vfxplatform.com)
        python-version: 3.9

    - name: Set up Visual Studio
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    - name: Cache conan packages
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: ~/conan
        key: ${{ matrix.config.os }}-conan

    - name: Install dependencies (Unix)
      if: runner.os != 'Windows'
      # Configure the system and install library dependencies via conan
      # packages.
      run: |
        source resources/build/bootstrap-${{ matrix.config.os }}.sh

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      # Configure the system and install library dependencies via conan
      # packages.
      run: |
        cmd /C resources\build\bootstrap-${{ matrix.config.os }}.bat

    - name: Configure CMake build
      shell: bash
      run: >
        cmake -S . -B build
        ${{ matrix.config.cmake-additional-args }}
        --install-prefix ${{ matrix.config.install-prefix }}
        --toolchain ${{matrix.config.toolchain }}
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DOPENASSETIO_ENABLE_TESTS=ON
        -DOPENASSETIO_ENABLE_SANITIZER_ADDRESS=${{ matrix.config.sanitizers }}
        -DOPENASSETIO_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=${{ matrix.config.sanitizers }}

    - name: Build, install and test
      run: |
        cd build
        ctest -VV

  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Test
      run: |
        echo "::add-matcher::./.github/workflows/problem-matchers/doxygen.json"
        # Problem matches don't actually error a step, so we have to
        # manually check for warnings/errors at the end. Capture the
        # output so we can parse it later.
        set -o pipefail
        make -C doc 2>&1 | tee doxygen-log.txt
        echo "::remove-matcher owner=doxygen::"
        # Fail the job if we have Doxygen warning/error lines in the
        # output. NB: This is the same regex as doxygen.json, adapted
        # to work with GNU grep.
        ! grep -qE "^.*?/src/[^:]+:[0-9]+: ?[a-zA-Z]+: ?.*$" doxygen-log.txt

    - name: Expose archive docs artifact
      uses: actions/upload-artifact@v2
      with:
        name: doxygen-documentation
        path: doc/html

  business-language:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Check business language
      run: |
        # Check that the acronym version of OpenAssetIO isn't in use
        # in the code base, see:
        #   https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/153
        # NB: The quotes deliberately avoid the string in question
        # appearing in this file, and failing the test.
        ! grep -ir "o""aio" .

