# A simple workflow to run tests using pytest against supported Python versions

name: Tests
on:
  pull_request:
    branches-ignore:
      - docs
    paths-ignore:
      - 'docs/**'

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache conan packages
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: ~/conan
        key: ${{ runner.os }}-conan

    - name: Install dependencies
      run: |
        source ci/bootstrap.sh

    - name: Configure
      run: |
        cmake -S . -B build \
          --install-prefix $GITHUB_WORKSPACE/dist \
          --toolchain $HOME/conan/conan_paths.cmake \
          -Wdev \
          -DOPENASSETIO_ENABLE_TESTS=ON \
          -DOPENASSETIO_WARNINGS_AS_ERRORS=ON \
          -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Build and test
      run: |
        cd build
        ctest -VV

  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Test
      run: |
        echo "::add-matcher::./.github/workflows/problem-matchers/doxygen.json"
        # Problem matches don't actually error a step, so we have to
        # manually check for warnings/errors at the end. Capture the
        # output so we can parse it later.
        set -o pipefail
        make -C doc 2>&1 | tee doxygen-log.txt
        echo "::remove-matcher owner=doxygen::"
        # Fail the job if we have Doxygen warning/error lines in the
        # output. NB: This is the same regex as doxygen.json, adapted
        # to work with GNU grep.
        ! grep -qE "^.*?/src/[^:]+:[0-9]+: ?[a-zA-Z]+: ?.*$" doxygen-log.txt

  business-language:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Check business language
      run: |
        # Check that the acronym version of OpenAssetIO isn't in use
        # in the code base, see:
        #   https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/153
        # NB: The quotes deliberately avoid the string in question
        # appearing in this file, and failing the test.
        ! grep -ir "o""aio" .

